# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xen_blkfront" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/xvdc";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/xvda";
      fsType = "ext2";
    };

  swapDevices =
    [ { device = "/dev/xvdb"; }
    ];

  nix.maxJobs = 1;
}
